recommerce/recycle_project/recycle_app/urls.py
from django.conf.urls import url
from recycle_app import views
from rest_framework import routers
from .api import ViewSet

# SET THE NAMESPACE!
app_name = 'recycle_app'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^user_logout/$',views.user_logout,name='user_logout'),
    url(r'^sell/$',views.sell,name='sell'),
    url(r'^buy/$',views.buy,name='buy'),
    url(r'^about/$',views.about,name='about'),

]

router=routers.DefaultRouter()
router.register('api/user',ViewSet,'recycle_app')

urlpatterns1=router.urls

recommerce/recycle_project/recycle_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from recycle_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^recycle_app/',include('recycle_app.urls')),
]

recommerce/recycle_project/recycle_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Add any additional attributes you want
    # portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    mobile_no = models.CharField(max_length=13,default='')


    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

recommerce/recycle_project/recycle_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from recycle_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())

    def clean(self):
        all_clean_data = super().clean()
        pword=all_clean_data['password']
        cword=all_clean_data['confirm_password']

        if pword!=cword:
            raise forms.ValidationError('make sure confirm password must match password')



    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('mobile_no',)

recommerce/recycle_project/recycle_app/views.py
from django.shortcuts import render
from recycle_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
    return render(request,'recycle_app/index.html')

def sell(request):
    return render(request,'recycle_app/sell.html')

@login_required
def buy(request):
    return render(request,'recycle_app/buy.html')

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            # if 'profile_pic' in request.FILES:
                # print('found it')
                # If yes, then grab it from the POST form reply
                # profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        # else:
            # One of the forms was invalid if this else gets called.
            # print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'recycle_app/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'recycle_app/login.html', {})

@login_required
def user_logout(request):

    logout(request)

    return HttpResponseRedirect(reverse('index'))


def about(request):
    return render(request,'recycle_app/about.html')

recommerce/recycle_project/templates/recycle_app/about.html
<!DOCTYPE html>
{% extends "recycle_app/base.html" %}
    {% block body_block%}

    <h1>what we do!</h1>
    <h1>recommerce </h1>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

    {% endblock %}

recommerce/recycle_project/templates/recycle_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'recycle_app:sell' %}">Sell</a></li>
          <li><a class="navbar-link" href="{% url 'recycle_app:buy' %}">Buy</a></li>
          <li><a class="navbar-link" href="{% url 'recycle_app:about' %}">About</a></li>
          <li><a class="navbar-link" href="{% url 'recycle_app:register'%}">Register</a></li>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'recycle_app:user_logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'recycle_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>


  </body>
</html>

recommerce/recycle_project/templates/recycle_app/buy.html
<!DOCTYPE html>
{% extends "recycle_app/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the Buyers page!</h1>


   {% endblock %}

recommerce/recycle_project/templates/recycle_app/index.html
<!DOCTYPE html>
{% extends "recycle_app/base.html" %}
    {% block body_block%}


  <h1>welcome to the recommerce</h1>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

     {% endblock %}

recommerce/recycle_project/templates/recycle_app/login.html
{% extends 'recycle_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'recycle_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <div class="form-group col-sm-6">
           <!-- <label for="exampleInputEmail1">Email address</label> -->
           <label for="username">Username:</label>
           <input type="text" name="username" placeholder="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
           <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
         </div>
          <!-- <label for="username">Username:</label>
          <input type="text" name="username" placeholder="username" required><br> -->
          <div class="form-group col-sm-6">

          <label for="password">Password</label>
          <input type="password" name="password" class="form-control" placeholder="password" required>


        </div>
          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

recommerce/recycle_project/templates/recycle_app/register.html
{% extends "recycle_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Create Account here </h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

recommerce/recycle_project/templates/recycle_app/sell.html
<!DOCTYPE html>
{% extends "recycle_app/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome the sales page!</h1>

    {% endblock %}